### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by anya427** [zjunlp/DocED#3]
Hello,I am trying to reproduce your code, but after I processed the ACE2005, I found the train.json is different from example_new.train your provided. Could you tell me if there are any other steps ?  Thanks!

**Comment by ldf2015311051** [comment]
> Hello,I am trying to reproduce your code, but after I processed the ACE2005, I found the train.json is different from example_new.train your provided. Could you tell me if there are any other steps ? Thanks!

The code we used for file parsing is from https://github.com/nlpcl-lab/ace2005-preprocessing.

**Comment by anya427** [comment]
I used  https://github.com/nlpcl-lab/ace2005-preprocessing to process the ACE2005, then I got three files (train.json dev.json test.json). Should I replace example_new.train with train.json in train_MLBiNet.py? Thanks!

**Comment by chensming** [comment]
> I used https://github.com/nlpcl-lab/ace2005-preprocessing to process the ACE2005, then I got three files (train.json dev.json test.json). Should I replace example_new.train with train.json in train_MLBiNet.py? Thanks!

Hey, bro, I also want to reproduce the code. Should we replace example_new.train with train.json in train_MLBiNet.py? Thank you!

**Comment by ldf2015311051** [comment]
> > I used https://github.com/nlpcl-lab/ace2005-preprocessing to process the ACE2005, then I got three files (train.json dev.json test.json). Should I replace example_new.train with train.json in train_MLBiNet.py? Thanks!
> 
> Hey, bro, I also want to reproduce the code. Should we replace example_new.train with train.json in train_MLBiNet.py? Thank you!

Yes.

**Comment by chensming** [comment]
> > > I used https://github.com/nlpcl-lab/ace2005-preprocessing to process the ACE2005, then I got three files (train.json dev.json test.json). Should I replace example_new.train with train.json in train_MLBiNet.py? Thanks!
> > 
> > 
> > Hey, bro, I also want to reproduce the code. Should we replace example_new.train with train.json in train_MLBiNet.py? Thank you!
> 
> Yes.

Thanks, bro. I'll give it a try. Hope you have a nice day!
