### ISSUE TITLE
关于预处理之后的数据处理问题

### ISSUE THREAD

**Issue by liu-yao-di** [zjunlp/DocED#4]
您好，最近想复现您在MLBiNet: A Cross-Sentence Collective Event Detection Network一文中的代码，但您在data-ACE中给出了exampe_new.dev，exampe_new.test，exampe_new.train三个数据文件，并且是单词--文件名--O O O（类似标注的形式给出的），但是https://github.com/nlpcl-lab/ace2005-preprocessing预处理之后的数据是sentence、golden-entity-mentions、words、pos-tags、parse、lemma，但您在论文中并没有使用到pos-tags、parse等特征，所以我猜想您应该有后续的处理工作，但不知道您后续对预处理之后的ACE数据集进行了哪些处理工作，不知道您是否愿意分享您预处理的代码，如果您愿意分享，将不胜感激。邮箱：1589807038@qq.com

[dev截图.docx](https://github.com/zjunlp/DocED/files/8357567/dev.docx)

**Comment by ldf2015311051** [comment]
是的，参考./data-ACE路径下的数据样例，我们只使用了实体的两级特征，其他解析结果没有入模。其中，两个层级的实体标签序列是直接结合实体标注结果和sentence内容生成的。希望解答了您的疑问，谢谢！
