### ISSUE TITLE
haha

### ISSUE THREAD

**Issue by 1996659** [zjunlp/DocED#6]
Can the ACE2005 dataset be released?

**Comment by zxlzr** [comment]
Hi, due to the license, the ACE2005 cannot be released, you can download the data from https://catalog.ldc.upenn.edu/LDC2006T06  and preprocess the data by https://github.com/nlpcl-lab/ace2005-preprocessing.

**Comment by 1996659** [comment]
请问一下在使用 https://github.com/nlpcl-lab/ace2005-preprocessing.预处理后的数据是怎么做的其他处理

**Comment by zxlzr** [comment]
您好，把数据转换成这种格式就行了https://github.com/zjunlp/DocED/blob/main/data-ACE/example_new.train

**Comment by 1996659** [comment]
好的，谢谢

**Comment by 1996659** [comment]
请问一下[example_new.train]数据后面的 o o o是依照什么规则标注的呢

**Comment by zxlzr** [comment]
您好，是序列标注的BIO标注体系。

**Comment by 1996659** [comment]
您好，请问一下您的序列标注用的是什么工具或者说是纯手工标注的吗

**Comment by zxlzr** [comment]
您可以参考https://github.com/zjunlp/DeepKE/blob/main/README_TAG_CN.md

使用工具https://github.com/doccano/doccano

**Comment by 1996659** [comment]
谢谢

**Comment by 1996659** [comment]
您好，请问一下这个标注的标签除了代码里给出的一部分，是不是还需要自己添加其他的
